"""
templates.py — Report structure templates.

Defines the layout, sections, and formatting rules for different
types of meeting reports. Templates are data-driven so the generator
can produce consistent output.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class ReportFormat(str, Enum):
    """Supported output formats."""

    DOCX = "docx"
    PDF = "pdf"
    HTML = "html"
    MARKDOWN = "markdown"
    JSON = "json"


class ReportStyle(str, Enum):
    """Visual style presets."""

    CORPORATE = "corporate"
    MINIMAL = "minimal"
    DETAILED = "detailed"


# ---------------------------------------------------------------------------
# Section definitions
# ---------------------------------------------------------------------------

class SectionConfig(BaseModel):
    """Configuration for a single report section."""

    key: str  # maps to AnalysisResult data key
    title: str
    icon: str = ""  # emoji for MD/HTML
    description: str = ""
    required: bool = False
    order: int = 0
    subsections: list[str] = Field(default_factory=list)


class ReportTemplate(BaseModel):
    """
    Full report template defining sections and styling.

    Templates are composable — you can include/exclude sections
    and reorder them based on meeting type.
    """

    name: str
    style: ReportStyle = ReportStyle.CORPORATE
    header_title: str = "Meeting Report"
    subtitle_template: str = "{meeting_title} — {meeting_date}"
    sections: list[SectionConfig] = Field(default_factory=list)
    include_toc: bool = True
    include_appendix: bool = False
    footer_text: str = "Generated by Intelligent Meeting Agent"

    # Styling
    primary_color: str = "#1a73e8"
    accent_color: str = "#174ea6"
    font_family: str = "Inter, Segoe UI, Roboto, sans-serif"


# ---------------------------------------------------------------------------
# Pre-built templates
# ---------------------------------------------------------------------------

FULL_REPORT_TEMPLATE = ReportTemplate(
    name="full_report",
    style=ReportStyle.CORPORATE,
    header_title="Meeting Intelligence Report",
    include_toc=True,
    include_appendix=True,
    sections=[
        SectionConfig(
            key="executive_summary",
            title="Executive Summary",
            icon="📋",
            description="High-level overview of the meeting",
            required=True,
            order=1,
        ),
        SectionConfig(
            key="key_topics",
            title="Key Topics Discussed",
            icon="💡",
            description="Main topics and discussion points",
            order=2,
            subsections=["topic", "summary", "discussed_by"],
        ),
        SectionConfig(
            key="decisions_made",
            title="Decisions Made",
            icon="✅",
            description="All decisions reached during the meeting",
            order=3,
            subsections=["decision", "made_by", "context"],
        ),
        SectionConfig(
            key="action_items",
            title="Action Items",
            icon="📌",
            description="Tasks assigned during the meeting",
            required=True,
            order=4,
            subsections=["action", "assignee", "deadline", "priority"],
        ),
        SectionConfig(
            key="sentiment_analysis",
            title="Sentiment & Tone Analysis",
            icon="🎭",
            description="Analysis of meeting dynamics and tone",
            order=5,
        ),
        SectionConfig(
            key="risks_and_concerns",
            title="Risks & Concerns",
            icon="⚠️",
            description="Risks and concerns raised",
            order=6,
            subsections=["risk", "severity", "raised_by"],
        ),
        SectionConfig(
            key="participant_engagement",
            title="Participant Engagement",
            icon="👥",
            description="How each participant contributed",
            order=7,
        ),
        SectionConfig(
            key="follow_up_items",
            title="Follow-up Items",
            icon="📅",
            description="Items requiring follow-up",
            order=8,
            subsections=["item", "responsible", "timeline"],
        ),
    ],
)

EXECUTIVE_SUMMARY_TEMPLATE = ReportTemplate(
    name="executive_summary",
    style=ReportStyle.MINIMAL,
    header_title="Executive Summary",
    include_toc=False,
    include_appendix=False,
    sections=[
        SectionConfig(
            key="executive_summary",
            title="Summary",
            icon="📋",
            required=True,
            order=1,
        ),
        SectionConfig(
            key="action_items",
            title="Key Action Items",
            icon="📌",
            order=2,
        ),
        SectionConfig(
            key="decisions_made",
            title="Key Decisions",
            icon="✅",
            order=3,
        ),
    ],
)

ACTION_ITEMS_TEMPLATE = ReportTemplate(
    name="action_items",
    style=ReportStyle.MINIMAL,
    header_title="Action Items Report",
    include_toc=False,
    sections=[
        SectionConfig(
            key="action_items",
            title="Action Items",
            icon="📌",
            required=True,
            order=1,
            subsections=["action", "assignee", "deadline", "priority", "context"],
        ),
        SectionConfig(
            key="follow_up_items",
            title="Follow-up Items",
            icon="📅",
            order=2,
        ),
    ],
)

# ---------------------------------------------------------------------------
# Template registry
# ---------------------------------------------------------------------------

TEMPLATES: dict[str, ReportTemplate] = {
    "full_report": FULL_REPORT_TEMPLATE,
    "executive_summary": EXECUTIVE_SUMMARY_TEMPLATE,
    "action_items": ACTION_ITEMS_TEMPLATE,
}


def get_template(name: str) -> ReportTemplate:
    """
    Get a report template by name.

    Args:
        name: Template name (e.g. 'full_report').

    Returns:
        The matching ReportTemplate.

    Raises:
        KeyError: If template name not found.
    """
    if name not in TEMPLATES:
        raise KeyError(f"Template '{name}' not found. Available: {list(TEMPLATES.keys())}")
    return TEMPLATES[name]


# ---------------------------------------------------------------------------
# Unit test stub
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    for name, tmpl in TEMPLATES.items():
        assert len(tmpl.sections) > 0
        print(f"  Template '{name}': {len(tmpl.sections)} sections")

    # Verify get_template
    full = get_template("full_report")
    assert full.name == "full_report"
    assert full.include_toc is True

    try:
        get_template("nonexistent")
        assert False, "Should have raised KeyError"
    except KeyError:
        pass

    print(f"✓ All {len(TEMPLATES)} templates validated")
